server:
  port: 9008
  error:
    include-stacktrace: never

spring:
  application:
    name: ms-inventario
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/inventario
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventario-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "cl.hilton.*"
        spring.json.use.type.headers: false
# formato base64
# tokenSecretKeyHotel2026HiltonSecurity
jwt:
  secret: "dG9rZW5TZWNyZXRLZXlIb3RlbDIwMjZIaWx0b25TZWN1cml0eQ=="
  expiration: 3600000

# [SWAGGER-INI] 
# Configuración de SpringDoc/Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# [SWAGGER-FIN] 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60