docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/01-init.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/02-habitaciones.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/03-huespedes.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/04-checkin.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/05-pagos.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/06-housekeeping.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/07-reservas.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/08-inventario.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/09-notificaciones.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/10-restaurante.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/11-reportes.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/12-autenticacion.sql
docker exec postgres-rdbms psql -U postgres -d postgres -f /docker-entrypoint-initdb.d/13-tarifas.sql